[package]
name = "otelx-sqlx"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.3", features = ["postgres"] }

otelx-core = { path = "../otelx-core" }
opentelemetry = "0.28.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
